config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#index"

  resources :recipes, path: "rezepte"

  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  post 'logout' => 'user_sessions#destroy', :as => :logout

  scope "/admin" do
    resources :ingredient_units, path: "zutaten-einheiten"
    resources :ingredients, path: "zutaten"
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :ingredient_unit
  belongs_to :recipe
  validates :name, :value, :ingredient_unit_id, presence: true
end

app/models/ingredient_list.rb
class IngredientList < ApplicationRecord
  belongs_to :ingredient_unit
  belongs_to :recipe
end

app/models/ingredient_unit.rb
class IngredientUnit < ApplicationRecord
  has_many :ingredients
  validates :name, presence: true
end

app/models/ingredients_list.rb
class IngredientsList < ApplicationRecord
  belongs_to :ingredient_unit
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy, inverse_of: :recipe
  belongs_to :user
  validates :title, :description, presence: true

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :recipes
  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private
  def not_authenticated
    redirect_to login_path, alert: "Du musst dich erst einloggen!"
  end

end

app/controllers/ingredient_units_controller.rb
class IngredientUnitsController < ApplicationController
  def index
    @ingredient_units = IngredientUnit.all
  end

  def new
    @ingredient_unit = IngredientUnit.new
  end

  def create
    @ingredient_unit = IngredientUnit.new(ingredient_unit_params)
    if @ingredient_unit.save
      flash[:notice] = "Einheit erfolgreich erstellt"
      redirect_to ingredient_units_path
    else
      flash[:alert] = "Einheit konnte nicht erstellt werden!"
      render "new"
    end
  end

  private
  def ingredient_unit_params
    params.require(:ingredient_unit).permit(:name, :shortcut)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:notice] = "Zutat wurde angelegt"
      redirect_to ingredients_path
    else
      flash[:alert] = "Zutat konnte nicht gespeichert werden"
      render "new"
    end
  end

  private
  def ingredient_params
    params.require(:ingredients).permit(:name, :value)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_login, only: [:index]
  
  def index
  end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:notice] = "Rezept wurde erfolgreich angelegt"
      redirect_to recipes_path
    else
      flash[:error] = "Upps... das Rezept konnte nicht gespeichert werden."
      render "new"
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    @ingredient_units = IngredientUnit.all
    @recipe.ingredients.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:notice] = "Rezept wurde erfolgreich angelegt"
      redirect_to recipes_path
    else
      flash[:error] = "Upps... das Rezept konnte nicht gespeichert werden."
      render "new"
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, ingredients_attributes: [:id, :name, :value, :ingredient_unit_id, :_destroy])
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to(:recipes, notice: 'Login erfolgreich')
    else
      flash.now[:alert] = 'Login fehlgeschlagen'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Du hast dich ausgeloggt')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User erfolgreich angelegt"
      redirect_to users_path
    else
      flash[:alert] = "User konnte nicht angelegt werden"
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User erfolgreich geändert"
      redirect_to users_path
    else 
      flash[:alert] = "User konnte nicht geändert werden"
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "User erfolgreich gelöscht"
      redirect_to users_path
    else
      flash[:alert] = "User konnte nicht gelöscht werden"
      redirect_to users_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :role, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/ingredient_units/_form.html.haml
= form_for @ingredient_unit do |f|  
  - if @ingredient_unit.errors.any?
    - @ingredient_unit.errors.each do |error, msg|
      = flash[:alert] = error, msg
  %div.flex.flex-col.mx-auto{:class => "w-4/5"}
    = f.text_field :name, placeholder: 'Name der Einheit', required: true, class:"bg-blue-100 mb-2 border-none rounded-md text-blue-900"
    = f.text_field :shortcut, placeholder: 'Abkürzung', required: true, class:"bg-blue-100 mb-2 border-none rounded-md text-blue-900"
    = f.submit "Einheit erstellen", class:"bg-blue-900 p-3 text-blue-100 rounded-md w-1/4 self-center hover:bg-blue-700 shadow-lg"

app/views/ingredient_units/index.html.haml
%h1 Eine Liste mit allen Einheiten für Zutaten 

- @ingredient_units.each do |unit|
  %ul
    %li 
      = unit.name
      (
      = unit.shortcut
      )

= link_to "Einheit erstellen", new_ingredient_unit_path 

app/views/ingredient_units/new.html.haml
%h1.text-3xl.text-center.font-semibold.my-5.text-blue-900 Neue Einheit für Zutaten anlegen
=render "form"

app/views/ingredients/index.html.haml
%h1 Liste aller Zutaten

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Familienrezepte
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "tailwind", "data-turbo-track": "reload"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body.bg-gray-200
    = render "shared/navbar"
    .container.mx-auto.px-4
      = render "shared/flash"
      = yield

app/views/pages/index.html.haml
%h1.font-serif.text-4xl.font-semibold.text-center.mt-3.text-gray-900 
  Familienrezepte das Familienkochbuch
.flex.flex-col.items-center
  %p.mt-4.text-center.text-gray-900{:class => "w-3/5"}
    Die Idee dieser Web-Applikation ist es, Rezepte unserer Familie zu sammeln und sie so an die nächste Generation weiterzugeben. Jeder innerhalb der Familie hat einige Spezialitäten, die so für jeden griffbereit zu finden sind.
  = image_tag "chefkoechin-marion.jpg", class: "object-fit object-center rounded-xl w-2/5 mt-4"

  %h2.font-serif.text-2xl.font-semibold.text-center.mt-4.text-gray-900  Marion wird 70 Jahre alt
  %p.mt-2.text-center.text-gray-900{:class => "w-3/5"}
    Entstanden ist die Seite anlässlich des 70. Geburtstag unserer Mutter, Oma und Schwiegermutter.

app/views/recipes/_form.html.haml
= form_for @recipe do |f|
  - if @recipe.errors.any?
    - @recipe.errors.each do |error, msg|
      = error
      = msg
  %div.flex.flex-col.mx-auto{:class => "w-4/5"}
    = f.text_field :title, placeholder: 'Name des Rezeptes', required: true, class:"bg-white shadow-xl mb-2 border-none rounded-md text-blue-900 outline-none"
    = f.hidden_field :user_id, value: current_user.id
    %div
      = f.fields_for :ingredients do |ingredient|
        = render "ingredient_fields", f: ingredient
      .flex.justify-center.my-2
        = link_to_add_association 'Weitere Zutat hinzufügen', f, :ingredients, class: "bg-gray-900 text-white rounded-xl px-3 py-2 shadow-lg"
    = f.text_area :description, placeholder: 'Zubereitung', rows: 15, required: true, class:"bg-white shadow-xl mb-2 border-none rounded-md text-blue-900 outline-none"
    = f.submit "Rezept erstellen", class:"bg-gray-900 p-3 text-white rounded-md w-1/4 self-center hover:bg-gray-700 shadow-lg"

app/views/recipes/_ingredient_fields.html.haml
.nested-fields.flex.justify-between
  = f.text_field :value, placeholder: "Menge eingeben", class:"bg-white shadow-xl mb-2 border-none rounded-md text-blue-900 outline-none"
  = f.collection_select :ingredient_unit_id, @ingredient_units, :id, :name, {prompt: "Wähle eine Maßeinheit"}, {class: "bg-white shadow-xl mb-2 border-none rounded-md text-blue-900 outline-none mx-3"}
  = f.text_field :name, placeholder: "Zutat eingeben", class:"bg-white shadow-xl mb-2 border-none rounded-md text-blue-900 outline-none flex-grow"
  .flex.items-center
    = link_to_remove_association (heroicon "x-circle", variant: :outline, options: {class: "text-red-900 mx-2 mb-2 w-7 h-7"}), f

app/views/recipes/index.html.haml
%h1.font-serif.text-4xl.font-semibold.text-center.mt-3.text-gray-900
  Alle Rezepte im Überblick

.grid.grid-cols-4.mt-4.w-full.gap-4
  - @recipes.each do |recipe|
    = link_to recipe_path(recipe) do
      = image_tag "spaghetti-example.jpg", class: "object-fit object-center rounded-xl"
      .text-center.text-2xl
        = recipe.title
      .text-sm.text-right
        von
        = recipe.user.name

app/views/recipes/new.html.haml
%h1.font-serif.text-4xl.font-semibold.text-center.mt-3.text-gray-900
  Neues Rezept erstellen
.mt-5
  = render "form"

app/views/recipes/show.html.haml
%h1.font-serif.text-4xl.font-semibold.text-center.mt-3.text-gray-900
  = @recipe.title

.flex.flex-col.items-center.mt-3
  = image_tag "spaghetti-example.jpg", class: "object-fit object-center w-3/5 rounded-xl"
  .text-sm.self-end
    ein rezept von
    = @recipe.user.name
%h2.font-serif.text-2xl.font-semibold.mt-2.text-gray-900
  Zutaten
%ul
  - @recipe.ingredients.each do |ingredient|
    %li.font-serif.text-xl.mt-1.text-gray-900
      = ingredient.value
      = ingredient.ingredient_unit.name
      = ingredient.name
%p.mt-3.p-4
  = @recipe.description

app/views/shared/_flash.html.haml
- if flash[:notice]
  .bg-green-200.text-green-800.py-2.text-center.m-2.rounded-md
    = flash[:notice]

- if flash[:alert]
  .bg-red-200.text-red-800.py-2.text-center.m-2.rounded-md
    = flash[:alert]

app/views/shared/_navbar.html.haml
%nav.sticky.top-0.z-50.grid.grid-cols-5.bg-gray-900.shadow-md.p-5.md:px-10
  = link_to root_path, class:"text-white relative flex items-center h-10 cursor-pointer" do
    = heroicon "home", variant: :outline, options: {class: "mr-3 w-6"}
    Home
  = link_to "Alle Rezepte", recipes_path, class:"text-white relative flex items-center h-10 cursor-pointer"
  = link_to "Rezept erstellen", new_recipe_path, class:"text-white relative flex items-center h-10 cursor-pointer"
  - if current_user
    .text-white.relative.flex.items-center.h-10.cursor-pointer
      = current_user.name
    .text-white.relative.flex.items-center.h-10.cursor-pointer
      = link_to "Logout", :logout, method: :post
  - else
    .text-white.relative.flex.items-center.h-10.cursor-pointer
      = link_to "Login", :login

app/views/user_sessions/_form.html.haml
= form_with url: login_path, method: :post do |f|
  %div.flex.flex-col.mx-auto{:class => "w-4/5"}
    = f.text_field :email, placeholder: "E-Mail eingeben", class:"bg-blue-100 mb-2 border-none rounded-md text-blue-900"
    = f.password_field :password, placeholder: "Passwort", class:"bg-blue-100 mb-2 border-none rounded-md text-blue-900"
    = f.submit "Login"

app/views/user_sessions/destroy.html.haml
%h1 UserSessions#destroy
%p Find me in app/views/user_sessions/destroy.html.haml

app/views/user_sessions/new.html.haml
%h1 Login
= render "form"

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    - @user.errors.full_messages.each do |msg|
      = flash[:alert] = msg
  %div.flex.flex-col.mx-auto{:class => "w-4/5"}
    = f.text_field :name, placeholder: 'Name des Users', required: true, class:"bg-blue-100 mb-2 border-none rounded-md text-blue-900"
    = f.text_field :email, placeholder: 'E-Mail des Users', required: true, class:"bg-blue-100 mb-2 border-none rounded-md text-blue-900"
    = f.text_field :role, placeholder: 'Rolle des Users', required: true, class:"bg-blue-100 mb-2 border-none rounded-md text-blue-900"
    = f.password_field :password, placeholder: 'Passwort', required: true, class:"bg-blue-100 mb-2 border-none rounded-md text-blue-900"
    = f.password_field :password_confirmation, placeholder: 'Passwort bestätigen', required: true, class:"bg-blue-100 mb-2 border-none rounded-md text-blue-900"
    = f.submit "User erstellen", class:"bg-blue-900 p-3 text-blue-100 rounded-md w-1/4 self-center hover:bg-blue-700 shadow-lg"

app/views/users/edit.html.haml
%h1 User ändern 
= render "form"

app/views/users/index.html.haml
%h1 Alle User
- @users.each do |user|
  %ul
    %li
    = link_to user_path(user) do
      = user.name
      |
      = user.email
      |
      = user.role

app/views/users/new.html.haml
%h1 User anlegen
= render "form"

app/views/users/show.html.haml
%h1 User Profil
= @user.name
= @user.email
= @user.role
= link_to "User bearbeiten", edit_user_path
= link_to "User löschen", user_path, method: "delete", data: { confirm: "Möchtest du den User wirklich löschen?" }